apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ngl92nsxr-python
  janus-idp.io/tekton: ngl92nsxr-python
  backstage.io/kubernetes-id: ngl92nsxr-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ngl92nsxr-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
