apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ngl92nsxr-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ngl92nsxr-python 
  name: ngl92nsxr-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ngl92nsxr-python 
